spring.application.name=chatapp
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Settings
spring.kafka.consumer.group-id=chat-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
chat.topic.name=chatroom1


